server.port=8181
spring.datasource.url=jdbc:sqlserver://213.156.198.49\\serverastra:1433;databaseName=recruting
spring.datasource.username=ganiushina
spring.datasource.password=aheronP@$$w0rd
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=none
spring.hibernate.connection.release_mode ="ON_CLOSE"

server.error.whitelabel.enabled=false
server.error.path=/error

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER


spring.jackson.serialization.indent_output=true

spring.thymeleaf.encoding=UTF-8

store.folder=${storefolder:Store}


spring.thymeleaf.prefix=classpath:/template/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


spring.mail.host=office.altapersonnel.ru
spring.mail.port=587
spring.mail.username=it@altapersonnel.ru
spring.mail.password=P@SSw0rd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

templatePath=email-templates/welcome-email
spring.thymeleaf.check-template-location=false



